@startuml

start

if     (условие 1) then (да)
  :Текст 1;
elseif (условие 2) then (да)
  :Срочное\nзавершение;
  stop
elseif (условие 3) then (да)
  :Текст 3;
elseif (условие 4) then (да)
  :Текст 4;
else (ничего не\nподходит)
  :Текст: ничего\nне подошло;
endif

:продолжение;

stop

@enduml
