@startuml

[*] --> Активная : активировать карту
state Активная {
    Обычная -[#green]-> Премиум : [статус клиента = VIP]
    Премиум -[#red]-> Обычная : [статус клиента != VIP]
}
Активная --> Утерянная : заявить об утере
Утерянная --> Заблокированная : заблокировать карту
Заблокированная --> Активная : разблокировать карту
Активная --> Заблокированная : заблокировать карту
Заблокированная --> [*] : закрыть карту
Активная --> Просроченная : [срок истек]
Просроченная --> Заблокированная : заблокировать карту
Активная --> Заблокированная : [попытка мошенничества]
Активная --> Заблокированная : [период неактивности >= 6 месяцев]

@enduml