@startuml
| менеджер |
start
repeat
if ( известен источник данных? ) then (нет)
    :отказаться от\nподготовки отчета;
    stop
else (да)
    :указать источник данных;
endif
| информационная система |
:загрузить данные;
backward :вывести уведомление\nоб отсутствии источника;
repeat while (данные загружены?) is ( нет ) not ( да )
switch ( источник данных? )
case ( csv-файл )
    if ( корректный формат? ) then ( да )
    else ( нет )
        | информационная система |
        #pink:вывести уведомление\nо нарушении формата;
        stop
    endif
case ( БД )
endswitch
if ( целостность нарушена? ) then ( да )
    #pink:вывести уведомление\nо нарушении целостности;
    stop
elseif ( есть дубликаты? ) then ( да )
    | информационная система |
    #pink:вывести уведомление\nо наличии дубликатов;
    stop
endif
repeat
    | менеджер |
    :подтвердить запуск генерации\nотчета на подготовленных данных;
    if ( запуск генерации подтвержден? ) then ( да )
        :задать условия фильтрации;
        :указать формат отчета;
    else ( нет )
        stop
    endif
    | информационная система |
    :агрегировать данные;
    | информационная система |
    :отфильтровать данные;
    | информационная система |
    :рассчитать метрики;
    :сгенерировать отчет;
backward :вывести уведомление о сбое\nпри генерации отчета;
repeat while ( отчет сгенерирован? ) is ( нет ) not ( да )
fork
    :отправить отчет;
fork again
    :сохранить отчет\nв облачное хранилище;
end fork
stop
@enduml